version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - nginx
    networks:
      - app-network
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./api/:/usr/app
      - /usr/app/node_modules
    networks:
      - app-network
  nginx:
    image: nginx:latest
    volumes:
      - ./backend/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - "4000:4000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
