version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
  nginx:
    image: nginx:latest
    volumes:
      - ./backend/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - "4000:4000"
